---
title: "First Knit"
author: "Leah Castro"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Antelope Valley Learning Academy. I graduated in 2024. I would say English is harder than Math because it is often more open ended and essays which I find more difficult. Math also has formulas and rules that make it easier to understand and work through. I always did best in English but Math was close behind. I enjoyed the challenge English gave me and Math always seemed boring at times which left me uninterested in work.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?
### my answer   
  I currently own a Lenovo windows thinkpad.I would rate myself a 7/10 in computer knowledge. I know the basics and how to get around and I am also confident I could r a problem out if I really tried.I have access to good internet but it is not entirely reliable an it dos go out a few times a year. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 
### my answer     
  My preferred name is my given name Leah pronounced Lay-uh.

   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to be an attorney. I think philosophy, AI law and ethics, and physics would be of greatest interests to me. I am currently trying to receive my political science degree and my software certificate at AVC. I intend to receive a political science or philosophy bachelors with a computer science minor or dual degree.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have only ever visited Mexico. I would love to go to Petra Jordan or Japan Tokyo. I have not been in the military but I think I would enjoy the Air Force if I had perfect vision as Ive always wanted to fly. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I am taking Math116. I did know. I need an A or B. I plan to try and stay on top of my work and understanding.
   
 






  




